[build]
  # static site (no build): leave command empty or remove the section.
  publish = "."

# ----- Headers -----
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600, immutable"

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Service-Worker-Allowed = "/"
    Cache-Control = "no-store, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

# ----- Redirects/Rewrites -----
# www → apex
[[redirects]]
  from = "https://www.falowen.app/*"
  to = "https://falowen.app/:splat"
  status = 301
  force = true

# Proxy everything else to Streamlit (MUST be last)
[[redirects]]
  from = "/*"
  to = "https://a1spreche.streamlit.app/:splat"
  status = 200
