name: Deploy Firebase (Hosting + Functions)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Auth with Google
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LANGUAGE_ACADEMY_3E1DE }}

      # If you don't have functions/package-lock.json, use npm install (not ci)
      - name: Install Functions deps
        run: npm install --prefix functions

      - name: Deploy Functions + Hosting (force)
        run: firebase deploy --project language-academy-3e1de --only functions,hosting --non-interactive --force
