
[server]
# These lines will be injected into your HTML <head>
head = """
  <title>Falowen – Your German Conversation Partner</title>
  <meta name="description" content="Falowen is your all-in-one German learning platform, powered by Learn Language Education Academy. Track streaks, submit assignments, watch lectures, practice vocab & writing, and more.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
"""
