[server]
# Allow your public front-ends to host the app
allowedOrigins = [
  "https://falowenappnew.netlify.app",
  "https://www.falowen.app",
  "https://falowen.app"
]

# These two make proxies simpler while we test. You can re-enable later.
enableCORS = false
enableXsrfProtection = false
